export const ActionTypes = {
    SET_COUNTRIES : 'SET_COUNTRIES',
    SELECTED_COUNTRY : 'SELECTED_COUNTRY',
    SEARCHED_COUNTRY : 'SEARCHED_COUNTRY',
    SEARCHED_TEXT : 'SEARCHED_TEXT',
    REMOVE_SEARCHED_TEXT : 'REMOVE_SEARCHED_TEXT',
    REMOVE_SELECTED_COUNTRY : 'REMOVE_SELECTED_COUNTRY'
}